### REQUESTS PARA LOS USUARIOS.
### Obtencion de todos los usuarios.
GET http://localhost:1234/usuarios

### Obtencion de los datos de un usuario en particular consignado por su número de id.
GET http://localhost:1234/usuarios/2

### Obtener el teléfono de un usuario que se indica por id.
GET http://localhost:1234/usuarios/telefono/2

### Obtener el nombre de un usuario que se indica por id.
GET http://localhost:1234/usuarios/nombre/1

### Guardar un usuario nuevo.
POST http://localhost:1234/usuarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzdWFyaW8iOiJqdWFuLnBlcmV6Iiwibml2ZWwiOjEsImV4cCI6MTY5NzIzNDA4MTE1NCwiaWF0IjoxNjk3MjM0MDIxfQ.bI-DHnn1Kw2PRbi7CBYuM4_orvynC1cr-JBoSvvl5A4

{
    "id": 13,
    "nombre": "Peter Paez",
    "edad": 22,
    "email": "peter@example.com",
    "telefono": "+9 111-333-13212",
}

###  Modificar algun atributo de usuario.
PATCH http://localhost:1234/usuarios/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzdWFyaW8iOiJqdWFuLnBlcmV6Iiwibml2ZWwiOjEsImV4cCI6MTY5NzIzNDA4MTE1NCwiaWF0IjoxNjk3MjM0MDIxfQ.bI-DHnn1Kw2PRbi7CBYuM4_orvynC1cr-JBoSvvl5A4

{
    "nombre": "Michael Salamanca"
}

### Borrar un usuario de los datos.
DELETE http://localhost:1234/usuarios/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzdWFyaW8iOiJqdWFuLnBlcmV6Iiwibml2ZWwiOjEsImV4cCI6MTY5NzIzNDA4MTE1NCwiaWF0IjoxNjk3MjM0MDIxfQ.bI-DHnn1Kw2PRbi7CBYuM4_orvynC1cr-JBoSvvl5A4

### REQUESTS PARA LOS PRODUCTOS
### Obtener el precio de un produto por id.
GET http://localhost:1234/productos/precio/5

### Obtener el nombre de un producto que se indica por id.
GET http://localhost:1234/productos/nombre/2

### Obtener el total del stock actual de productos, la sumatoria de los precios individuales.
GET http://localhost:1234/productos

### OTROS REQUESTS
### Simular formulario de loggeo.

POST http://localhost:1234/auth
Content-Type: application/json

    {
        "usuario": "juan.perez",
        "password": "juan123"
    }

